ExamenFinal/urls.py
from django.urls import path
from miapp import views


urlpatterns = [
    path('', views.inicio, name='inicio'),


    path('editoriales/', views.listar_editoriales, name='editoriales'),
    path('crear_editorial/', views.crear_editorial, name='crear_editorial'),
    path('eliminar_editorial/<int:carrera_id>/', views.eliminar_editorial, name='eliminar_editorial'),
    path('editar_editorial/<int:carrera_id>/', views.editar_editorial, name='editar_editorial'),  # Verifica esta línea

    path('paises/', views.listar_paises, name='paises'),
    path('crear_pais/', views.crear_pais, name='crear_pais'),
    path('eliminar_pais/<int:idcurso>/', views.eliminar_pais, name='eliminar_pais'),
    path('modificar_pais/<int:idcurso>/', views.modificar_pais, name='modificar_pais'),

]
from django.conf import settings
from django.conf.urls.static import static

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

miapp/models.py
# mi_aplicacion/models.py
from django.db import models

class Career(models.Model):
    idcareer = models.AutoField(primary_key=True)
    name = models.CharField(max_length=100)
    shortname = models.CharField(max_length=20)
    image = models.ImageField(upload_to='careers/', null=True, blank=True) # Usa ImageField para las imágenes
    state = models.BooleanField(default=True)

    def __str__(self):
        return self.name

# models.py
from django.db import models

class Course(models.Model):
    idcourse = models.AutoField(primary_key=True)
    code = models.CharField(max_length=10)
    name = models.CharField(max_length=100)
    hour = models.IntegerField()
    state = models.BooleanField(default=True)

    def __str__(self):
        return self.name

miapp/views.py
from django.shortcuts import render

def inicio(request):
    return render(request, 'inicio.html')

#def carreras(request):
 #   return render(request, 'carreras.html')

#def crear_carrera(request):
 #   return render(request, 'crear_carrera.html')

# mi_aplicacion/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib import messages
from .models import Career

def listar_editoriales(request):
    editoriales = Career.objects.all()
    return render(request, 'editoriales.html', {'editoriales': editoriales})

def crear_editorial(request):
    if request.method == 'POST':
        name = request.POST['name']
        shortname = request.POST['shortname']
        image = request.FILES.get('image')  # Usa request.FILES para obtener la imagen enviada

        # Obtenemos el valor del campo state como un string ('on' o None)
        state_str = request.POST.get('state', None)

        # Convertimos el string a un valor booleano válido (True o False)
        state = True if state_str == 'on' else False

        Career.objects.create(name=name, shortname=shortname, image=image, state=state)
        messages.success(request, 'Carrera agregada exitosamente.')
        return redirect('editoriales')

    return render(request, 'crear_editorial.html')

def eliminar_editorial(request, carrera_id):
    editorial = get_object_or_404(Career, idcareer=carrera_id)
    editorial.delete()
    messages.success(request, 'Carrera eliminada exitosamente.')
    return redirect('editoriales')

def editar_editorial(request, carrera_id):
    editorial = get_object_or_404(Career, idcareer=carrera_id)
    if request.method == 'POST':
        if 'name' in request.POST:
            editorial.name = request.POST['name']
        if 'shortname' in request.POST:
            editorial.shortname = request.POST['shortname']
        if 'image' in request.FILES:
            editorial.image = request.FILES['image']
        if 'state' in request.POST:
            editorial.state = request.POST.get('state') == 'on'
        editorial.save()
        messages.success(request, 'Carrera actualizada exitosamente.')
        return redirect('editoriales')

    return render(request, 'editar_editorial.html', {'editorial': editorial})

##----------------------------------------------------------

# views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import Course
from django.contrib import messages

def listar_paises(request):
    paises = Course.objects.all()
    return render(request, 'paises.html', {'paises': paises})

def crear_pais(request):
    if request.method == 'POST':
        # Obtener datos del formulario
        code = request.POST['code']
        name = request.POST['name']
        hour = request.POST['hour']
        state = True if 'state' in request.POST else False

        # Crear y guardar el nuevo curso en la base de datos
        pais = Course(code=code, name=name, hour=hour, state=state)
        pais.save()

        # Mostrar mensaje de éxito
        messages.success(request, 'Pais agregado correctamente.')

        # Redireccionar a la lista de cursos
        return redirect('paises')

    return render(request, 'crear_pais.html')

def eliminar_pais(request, idcurso):
    pais = get_object_or_404(Course, idcourse=idcurso)
    pais.delete()
    messages.success(request, 'Pais eliminado exitosamente.')
    return redirect('paises')

def modificar_pais(request, idcurso):
    # Buscar el curso por su ID
    pais = get_object_or_404(Course, pk=idcurso)

    if request.method == 'POST':
        # Obtener datos del formulario enviado
        code = request.POST['code']
        name = request.POST['name']
        hour = request.POST['hour']
        state = True if 'state' in request.POST else False

        # Modificar los datos del curso
        pais.code = code
        pais.name = name
        pais.hour = hour
        pais.state = state
        pais.save()

        # Mostrar mensaje de éxito
        messages.success(request, 'Pais modificado correctamente.')

        # Redireccionar a la lista de cursos
        return redirect('paises')

    return render(request, 'modificar_pais.html', {'pais': pais})

miapp/templates/crear_editorial.html
{% extends 'inicio.html' %}

<!-- agregar_carrera.html -->

{% block title %}Agregar Editorial{% endblock %}

{% block content %}
<div style="display: flex; justify-content: center; align-items: center; height: 100%vh;">
    <div style="width: 20%;">
    <h1>Agregar Editorial</h1>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <label for="id_name" style="display: block; margin-bottom: 5px;">Nombre:</label>
        <input type="text" name="name" id="id_name" style="width: 100%; padding: 5px; margin-bottom: 10px;">
        
        <label for="id_shortname" style="display: block; margin-bottom: 5px;">Nombre corto:</label>
        <input type="text" name="shortname" id="id_shortname" style="width: 100%; padding: 5px; margin-bottom: 10px;">
        
        <label for="id_image" style="display: block; margin-bottom: 5px;">Imagen:</label>
        <input type="file" name="image" id="id_image" style="width: 100%; padding: 5px; margin-bottom: 10px;">
        
        <label for="id_state" style="display: block; margin-bottom: 5px;">Estado:</label>
        <input type="checkbox" name="state" id="id_state" style="margin-right: 5px;"><br>
        
        <input type="submit" value="Guardar" style="background-color: #4CAF50; color: #fff; padding: 10px 15px; border: none; cursor: pointer;">
    </form>
</div>
</div>
{% endblock %}

miapp/templates/crear_pais.html
{% extends 'inicio.html' %}

{% block title %}Agregar Pais{% endblock %}

{% block content %}
    <h1>Agregar Pais</h1>
{% endblock %}

miapp/templates/editar_editorial.html
<!-- editar_carrera.html -->
{% extends 'inicio.html' %}


{% block title %}Editar Editorial{% endblock %}

{% block content %}
<div style="display: flex; justify-content: center; align-items: center; height: 100%vh;">
    <div style="width: 20%;">
    <h1>Editar Editorial</h1>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <label for="id_name" style="display: block; margin-bottom: 5px;">Nombre:</label>
        <input type="text" name="name" id="id_name" value="{{ editorial.name }}" style="width: 100%; padding: 5px; margin-bottom: 10px;">
        
        <label for="id_shortname" style="display: block; margin-bottom: 5px;">Nombre corto:</label>
        <input type="text" name="shortname" id="id_shortname" value="{{ editorial.shortname }}" style="width: 100%; padding: 5px; margin-bottom: 10px;">
        
        <label for="id_image" style="display: block; margin-bottom: 5px;">Imagen:</label>
        <input type="file" name="image" id="id_image" style="width: 100%; padding: 5px; margin-bottom: 10px;">
        
        <label for="id_state" style="display: block; margin-bottom: 5px;">Estado:</label>
        <input type="checkbox" name="state" id="id_state" {% if editorial.state %}checked{% endif %} style="margin-right: 5px;"><br>
        
        <input type="submit" value="Guardar" style="background-color: #4CAF50; color: #fff; padding: 10px 15px; border: none; cursor: pointer;">
    </form>
</div>
</div>
{% endblock %}

miapp/templates/editoriales.html
{% extends 'inicio.html' %}

<!-- carreras.html -->

{% block title %}Listado de Editoriales{% endblock %}

{% block content %}
<div style="display: flex; justify-content: center; align-items: center; height: 100%vh;">
    <div style="width: 60%;">
    <h1>Listado de Editoriales</h1>
    <table style="width: 100%; border-collapse: collapse;">
        <thead>
            <tr style="background-color: #f2f2f2;">
                <th style="padding: 10px; border: 1px solid #ccc;">ID</th>
                <th style="padding: 10px; border: 1px solid #ccc;">Nombre</th>
                <th style="padding: 10px; border: 1px solid #ccc;">Nombre corto</th>
                <th style="padding: 10px; border: 1px solid #ccc;">Imagen</th>
                <th style="padding: 10px; border: 1px solid #ccc;">Estado</th>
                <th style="padding: 10px; border: 1px solid #ccc;">Acciones</th>
            </tr>
        </thead>
        <tbody>
            {% for editorial in editoriales %}
                <tr>
                    <td style="padding: 10px; border: 1px solid #ccc;">{{ editorial.idcareer }}</td>
                    <td style="padding: 10px; border: 1px solid #ccc;">{{ editorial.name }}</td>
                    <td style="padding: 10px; border: 1px solid #ccc;">{{ editorial.shortname }}</td>
                    <td style="padding: 10px; border: 1px solid #ccc;"><img src="{{ editorial.image.url }}" alt="{{ editorial.name }}" width="50"></td>
                    <td style="padding: 10px; border: 1px solid #ccc;">{% if carrera.state %}Activa{% else %}Inactiva{% endif %}</td>
                    <td style="padding: 10px; border: 1px solid #ccc;">
                        <a href="{% url 'editar_editorial' editorial.idcareer %}">Editar</a>
                        <a href="{% url 'eliminar_editorial' editorial.idcareer %}">Eliminar</a>
                    </td>
                </tr>
            {% endfor %}
        </tbody>
    </table>

</div>
</div
    
{% endblock %}

miapp/templates/inicio.html
<!DOCTYPE html>
<html>
<head>
    <title>Mi Proyecto - {% block title %}{% endblock %}</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            margin: 0;
            padding: 0;
            background-color: #f0f0f0;
        }
        
        .header {
            text-align: center;
            background-color: #333;
            padding: 10px;
        }
        
        .header img {
            max-width: 350px; /* Establecemos un ancho máximo para el logotipo */
        }
        
        .menu {
            background-color: #333;
            padding: 10px;
            text-align: center;
        }
        
        .menu ul {
            list-style: none;
            margin: 0;
            padding: 0;
            display: inline-block;
        }
        
        .menu ul li {
            display: inline-block;
            margin-right: 20px;
        }
        
        .menu ul li a {
            color: #fff;
            text-decoration: none;
        }
        
        .menu ul li a:hover {
            color: #ffcc00;
        }
        
        .content {
            text-align: center;
            margin-top: 30px;
            border: 1px solid #ccc; /* Agregamos un borde para encuadrar el contenido */
            padding: 20px; /* Agregamos un espacio interno para separar el contenido del borde */
        }
        
    </style>
</head>
<body>
    <div class="header">
        <img src="https://www.untels.edu.pe/images/logo.png" alt="Logo de Mi Proyecto">
    </div>
    <div class="menu">
        <ul>
            <li><a href="{% url 'editoriales' %}">Editoriales</a></li>
            <li><a href="{% url 'crear_editorial' %}">Crear Editorial</a></li>
            <li><a href="{% url 'paises' %}">Paises</a></li>
            <li><a href="{% url 'crear_pais' %}">Crear Pais</a></li>
        </ul>
    </div>
    <div class="content">
        {% block content %}
        {% endblock %}
    </div>
</body>
</html>

miapp/templates/modificar_pais.html
{% extends 'inicio.html' %}
{% block title %}Modificar Pais{% endblock %}

{% block content %}
<div style="display: flex; justify-content: center; align-items: center; height: 100%;">
    <div style="width: 20%;">
        <h1>Modificar Pais</h1>
        <form method="post">
            {% csrf_token %}
            <label for="id_code" style="display: block; margin-bottom: 5px;">Código:</label>
            <input type="text" name="code" id="id_code" value="{{ curso.code }}" style="width: 100%; padding: 5px; margin-bottom: 10px;">
            
            <label for="id_name" style="display: block; margin-bottom: 5px;">Nombre:</label>
            <input type="text" name="name" id="id_name" value="{{ curso.name }}" style="width: 100%; padding: 5px; margin-bottom: 10px;">
            
            <label for="id_hour" style="display: block; margin-bottom: 5px;">Horas:</label>
            <input type="number" name="hour" id="id_hour" value="{{ curso.hour }}" style="width: 100%; padding: 5px; margin-bottom: 10px;">
            
        
            
            <label for="id_state" style="display: block; margin-bottom: 5px;">Estado:</label>
            <input type="checkbox" name="state" id="id_state" {% if curso.state %}checked{% endif %} style="margin-right: 5px;"><br>
            
            <input type="submit" value="Guardar" style="background-color: #4CAF50; color: #fff; padding: 10px 15px; border: none; cursor: pointer;">
        </form>
    </div>
</div>
{% endblock %}

miapp/templates/paises.html
{% extends 'inicio.html' %}

<!-- cursos.html -->

{% block title %}Listado de Cursos{% endblock %}

{% block content %}
    <div style="display: flex; justify-content: center; align-items: center; height: 100%;">
        <div style="width: 80%;">
            <h1>Listado de Paises</h1>
            <table style="width: 100%; border-collapse: collapse;">
                <thead>
                    <tr style="background-color: #f2f2f2;">
                        <th style="padding: 10px; border: 1px solid #ccc;">ID</th>
                        <th style="padding: 10px; border: 1px solid #ccc;">Código</th>
                        <th style="padding: 10px; border: 1px solid #ccc;">Nombre</th>
                        <th style="padding: 10px; border: 1px solid #ccc;">Horas</th>
                  
                        <th style="padding: 10px; border: 1px solid #ccc;">Estado</th>
                        <th style="padding: 10px; border: 1px solid #ccc;">Acciones</th>
                    </tr>
                </thead>
                <tbody>
                    {% for pais in paises %}
                        <tr>
                            <td style="padding: 10px; border: 1px solid #ccc;">{{ pais.idcourse }}</td>
                            <td style="padding: 10px; border: 1px solid #ccc;">{{ pais.code }}</td>
                            <td style="padding: 10px; border: 1px solid #ccc;">{{ pais.name }}</td>
                            <td style="padding: 10px; border: 1px solid #ccc;">{{ pais.hour }}</td>
                           
                            <td style="padding: 10px; border: 1px solid #ccc;">{% if pais.state %}Activo{% else %}Inactivo{% endif %}</td>
                            <td style="padding: 10px; border: 1px solid #ccc;">                            
                            <a href="{% url 'modificar_pais' idcurso=pais.idcourse %}">Modificar</a>
                            <a href="{% url 'eliminar_pais' pais.idcourse %}">Eliminar</a>
                            </td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
{% endblock %}